/*
 *SOLVING MATHS PROBLEM.
 *FETURE:
 *FIND ROOT OF QUADRATIC EQUATION.
 *FIND EIGN VALUES AND EQUATION OF MATRIX.
 *FING LOG VALUE OF ANY NUMBER.
 *FIND INVERSE MATRIX.
 *FIND SIN X,COS X..ETC VALUES(where X is any  angle).
 */